### ISSUE TITLE
Update to PlatformIO 5.2.5

### ISSUE THREAD

**Issue by amandel** [Andreas-Huber/platformio-docker-for-ci#14]
Thanks for your container. We use it to build https://github.com/openbikesensor/OpenBikeSensorFirmware. 

Do you plan to do a update? Currently we get `There is a new version 5.2.5 of PlatformIO available.`

**Comment by Andreas-Huber** [comment]
Thanks for the issue. I completely forgot about it. This was automated before, but docker turned off the automatic builds for free users.
I will update it, just not today or tomorrow.
Will automate it another way.

**Comment by Andreas-Huber** [comment]
Updated to 6.1.1 and the upcoming versions are built now again automatically once a new version of platformio is released. Just by github actions and not docker hub builds.
