### ISSUE TITLE
Add documentation on how to test the compilation locally

### ISSUE THREAD

**Issue by Andreas-Huber** [Andreas-Huber/platformio-docker-for-ci#2]
Add documentation on how to test the compilation locally.
Document how to run PlatformIO in the docker image.

- Add commands from Dirneis script to Documentation
- Update the Azure Pipelines example to use the example code.

**Comment by Dirnei** [comment]
if you wan't i can add a hello-world arduino example

**Comment by Andreas-Huber** [comment]
Sure, why not :-) That's what I had in mind.
A hello world is in that private repo already.
https://infinite-coding.visualstudio.com/CiTestsAndSamples/_git/PlatformIOCiSample

Don't know what makes more sense - an examples folder or readme or put it just into the readme.
I would argue readme, because that's visible on docker hub.

**Comment by Dirnei** [comment]
I would have done both :) Maybe also a powershell script which runs the build in the docker locally

**Comment by Dirnei** [comment]
I created a branch named "example" with basic a platformio project and a powershell script to build the dockerfile and the platformio project afterwards.

**Comment by Andreas-Huber** [comment]
Looks good, I would change the examples to use the online version of the code and not require the local docker file.

**Comment by Dirnei** [comment]
I added it as a second script. Maybe the first one is good for a ci build for this project.
